version: '3.7'

services:
  nginx:
    image: nginx
    container_name: ${NGINX_NAME}
    ports:
      - 80:80
      # - 443:443
    restart: always
    depends_on:
      - web
    volumes:
      - ./static:/usr/projects/${PROJECT_NAME}/static
      # - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d

  web:
    build:
      context: .
      args:
        - PROJECT_NAME
    container_name: ${PROJECT_NAME}
    image: ${IMAGE_NAME}
    command: bash -c "cd src/ && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 config.wsgi --reload"
    restart: always
    # depends_on:
    #   - db
    ports:
      - 8000:8000
    volumes:
      - .:/usr/projects/${PROJECT_NAME}
    environment:
      - LEVEL
