version: '3.1'

services:
  db:
    container_name: <mysql-name>
    image: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - /usr/projects/mysql/<mysql-name>:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
