version: '3.7'

services:
  db:
    container_name: ${MYSQL_NAME}
    image: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /usr/projects/mysql/${MYSQL_NAME}:/var/lib/mysql
    environment:
      - MYSQL_ROOT_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
