version: '3.7'

services:
  db:
    container_name: ${POSTGRES_NAME}
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /usr/projects/psql/${POSTGRES_NAME}:/var/lib/psql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
