version: '3.1'

services:
  db:
    container_name: <psql-name>
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /usr/projects/psql/<psql-name>:/var/lib/psql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
